
name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        ASPNETCORE_ENVIRONMENT: Production

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Save firebase.json from secret
        run: echo "${{ secrets.FIREBASE_JSON }}" > firebase.json

      - name: Validate firebase.json
        run: cat firebase.json | jq '.'

      - name: Save production.json from secret
        run: echo "${{ secrets.PROD_JSON }}" > appsettings.Production.json

      - name: Validate production.json
        run: cat appsettings.Production.json
      - name: Build Docker Image | jq '.'
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/devkid_api:latest .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/devkid_api:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: SSH and deploy
        env:
            API_KEY: ${{ secrets.API_KEY }}
            CHECKSUM_KEY: ${{ secrets.CHECKSUM_KEY }}
            CLIENT_ID: ${{ secrets.CLIENT_ID }}
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/devkid_api:latest
            cd /etc/docker
            docker compose up --build -d